Document: teampass
Title: Debian teampass Manual
Author: <insert document author here>
Abstract: This manual describes what teampass is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/teampass/teampass.sgml.gz

Format: postscript
Files: /usr/share/doc/teampass/teampass.ps.gz

Format: text
Files: /usr/share/doc/teampass/teampass.text.gz

Format: HTML
Index: /usr/share/doc/teampass/html/index.html
Files: /usr/share/doc/teampass/html/*.html
